export const SCOUT_ACTIONS = ["CHECK_BALANCES", "SEARCH_TOKEN"];

export const STRATEGIST_ACTIONS = ["POST_TWEET", "POST_BOUNTY"];

export const EXECUTOR_ACTIONS = [
  "CHECK_BALANCES",
  "SEARCH_TOKEN",
  "TRANSFER",
  "TRADE_TOKENS",
  "LAUNCH_PUMPFUN_TOKEN",
  "BUY_PUMPFUN_TOKEN",
  "SELL_PUMPFUN_TOKEN",
];
